# Generated by Django 6.0.3 on 2026-03-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topiclink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("youtube", "YouTube"),
                    ("doc", "Document"),
                    ("image", "Image"),
                ],
                max_length=20,
            ),
        ),
    ]
