# Generated by Django 6.0.3 on 2026-03-07 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0004_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="topic_documents/")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("notes", "Notes"),
                            ("assignment", "Assignment"),
                            ("other", "Other"),
                        ],
                        default="notes",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="syllabus.topic",
                    ),
                ),
            ],
        ),
    ]
